
typedef enum _EMessageType
{
	MT_CHAT = 1,
	MT_DISCONNECT_NOTIFY = 2,
	MT_ERROR_NOT_JOINED = 3,
	MT_JOIN_ACCEPTED = 4,
	MT_JOIN_DENIED = 5,
	MT_JOIN_NOTIFY = 6,
	MT_JOIN_REQUEST = 7,
	MT_KEEP_ALIVE = 8,
	MT_QUIT_NOTIFY = 9,
	MT_QUIT_REQUEST = 10,
	MT_SERVER_AVAILABLE = 11,
	MT_SERVER_DETECT = 12
} EMessageType;
